#!/usr/bin/python

import sys
import os

def sys_arg_v_string():
    string = ''
    for arg in sys.argv[1:]:
        string += '"' + arg + '" '
    return string[:-1]

os.system("cargo build")
if sys.platform == "linux":
    os.system("valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=memorylog.txt ./target/debug/frho " + sys_arg_v_string())
else:
    print("Your platform isn't supported")